ALTER TABLE public.site_settings
  ADD COLUMN IF NOT EXISTS ga4_id text,
  ADD COLUMN IF NOT EXISTS gtm_id text,
  ADD COLUMN IF NOT EXISTS fb_pixel_id text,
  ADD COLUMN IF NOT EXISTS head_html text,
  ADD COLUMN IF NOT EXISTS body_html text,
  ADD COLUMN IF NOT EXISTS adsense_client text,
  ADD COLUMN IF NOT EXISTS adsense_slot_header text,
  ADD COLUMN IF NOT EXISTS adsense_slot_inline text,
  ADD COLUMN IF NOT EXISTS adsense_slot_sidebar text,
  ADD COLUMN IF NOT EXISTS adsense_slot_sticky_mobile text,
  ADD COLUMN IF NOT EXISTS adsense_enabled boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS adsense_auto_ads boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS slot_header_enabled boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS slot_inline_enabled boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS slot_sidebar_enabled boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS slot_sticky_mobile_enabled boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS ads_txt text,
  ADD COLUMN IF NOT EXISTS default_og_image text,
  ADD COLUMN IF NOT EXISTS default_meta_description text,
  ADD COLUMN IF NOT EXISTS title_template text NOT NULL DEFAULT '%s | Calcy',
  ADD COLUMN IF NOT EXISTS gsc_verification text,
  ADD COLUMN IF NOT EXISTS bing_verification text,
  ADD COLUMN IF NOT EXISTS robots_txt text,
  ADD COLUMN IF NOT EXISTS indexing_enabled boolean NOT NULL DEFAULT true;